#!/usr/bin/env sh

INGESTION_DIR=ingestion

ie_dd=$(dirname $0)

ing_dir=$ie_dd/$INGESTION_DIR
if [[ ! -d $ing_dir ]]
then
  echo "FATAL: missing subdirectory '$ing_dir', exiting"
  exit 2
fi

cd $ie_dd

#get port number from ingestion_config.json, if any
nn=($(grep ie_server_port ingestion_config.json))
if [ $? == 0 ]
then
    TMP_IE_PORT=$(echo ${nn[2]} | sed s/,//)
fi

DREAM_IE_IE_PORT=${TMP_IE_PORT:-$1}

if [[ ! -d $INGESTION_DIR/static/db ]]
then
  mkdir $INGESTION_DIR/static/db
fi

if [[ ! -f $INGESTION_DIR/static/db/dream.db ]]
then
  ./manage.py syncdb --noinput
fi
if [ $? == 0 ]
then
  ./manage.py runserver  $DREAM_IE_IE_PORT
fi
